name: "Danger JS"
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Danger JS
        uses: danger/danger-js@10.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}